### Install (if needed) and Import Libraries

In [1]:
import requests as re
import json
import sys
import pymysql
from sqlalchemy import create_engine
import pandas as pd

### Conection to Google Cloud Database to import table 'words'

In [2]:
driver = 'mysql+pymysql'
ip = ''
username = ''
password = ''
db = ''

cs  = f'{driver}://{username}:{password}@{ip}/{db}'
engine = create_engine(cs)

In [3]:
Ssql = '''SELECT 
    word, 
    interactions, 
    appearances, 
    round((interactions)/(appearances),2) as eng_ratio 
FROM words 
ORDER by round((interactions)/(appearances),2) desc, appearances'''

words = pd.read_sql(Ssql,engine)
words = words[['word','interactions', 'appearances', 'eng_ratio']]

In [4]:
words[words['word'].apply(lambda x: len(x)>3)].head(20)

                  word  interactions  appearances  eng_ratio
0                Baila          1367            1    1367.00
1              hubiera          1367            1    1367.00
2              mirando          1367            1    1367.00
3           Entrañable          1367            1    1367.00
4               escena          1367            1    1367.00
5              lección          1367            1    1367.00
6             bailando          1367            1    1367.00
7                nadie          1438            3     479.33
8           #Ampliamos           479            1     479.00
9             custodia           479            1     479.00
10               firme           479            1     479.00
11         entregarlo…           479            1     479.00
12          #Exclusiva           456            1     456.00
15  #DiaMundialAutismo           444            1     444.00
16         emocionante           444            1     444.00
17           pronuncia           444            1     444.00
18            primera…           444            1     444.00
19               padre          1443            4     360.75
20              Síndic           349            1     349.00
21             recorre           349            1     349.00

In [7]:
words[words['word'].apply(lambda x: len(x)>3)].tail(10)

             word  interactions  appearances  eng_ratio
7092       inicio             0            2        0.0
7093         llei             0            2        0.0
7095     mientras             0            2        0.0
7096  consecutivo             0            2        0.0
7097       puedes             0            2        0.0
7098       Varios             0            2        0.0
7099      heridos             0            2        0.0
7100     homenaje             0            2        0.0
7101        tiros             0            2        0.0
7102       buenos             0            3        0.0